### PR TITLE
Optimizations that do NOT change functionality

### PR DESCRIPTION
**Pull request by redhog**
This PR contains a set of optimizations that all center around not calculating the same thing multiple times. This represents a 4x speedup or thereabout.

### CODE REVIEW

**Comment by mmaelicke** [comment]
@redhog thank you so much for your contributions! So many problems solved and quick n' dirty stuff removed, that had been on my agenda for quite some time. Great.
Unfortunately, the unittests of these two new PRs also fail at the same spots with the same messages. I am not so sure if it was really your code in the first place, unless this PR is build by any chance on top of PR #40 ?  
I'll dig into that tomorrow, to understand what is going on.

I really like your masking solution.

**Comment by redhog** [comment]
Yeah, they're built on top of each other, sorry. I started hacking on the code, realized it was too big a chunk to submit as one PR and split it in three, but without rebasing...

**Review by mmaelicke — APPROVED** [review]
Much more elegant. Finally, you made this ugly __vdiff_indexer obsolete, thanks!

@redhog , will you merge the current master into your optimization branch first, to update the changes of #45 (and therefore the unittests work), or should I create a new PR for that?

**Comment by redhog** [comment]
Merged master into my PR:s :)

**Pull request merged**
