### PR TITLE
Separate class to store variogram results in

### PR DESCRIPTION
**Pull request by redhog**
This class lets you store variogram result parameters (sill, range, nugget as well as metrics used etc) without the coordinates and values, making the pickle size much smaller. It also allows you to re-add the coordinates and values, or possibly other coordinates and values for special cases.

### CODE REVIEW

**Comment by mmaelicke** [comment]
Maybe it's just the class name proposed for this new class, but I'm not 100% happy with this enhancement. 
I would hesitate to offer a possibility to store or even use a variogram model without the context of its data. For me, a model is only useful, when I know where the parameters come from and how they were estimated. Moreover, if we make it possible to pass new data (coordinates, values) to that instance, but keep the old parameters, that can easily lead to wrong assumptions about the model, doesn't it?

If it's just about storing parameters somewhere, there  are 
https://github.com/mmaelicke/scikit-gstat/blob/bab68cf32551595bf66430e0354dbafba44d3573/skgstat/Variogram.py#L1409

and 
https://github.com/mmaelicke/scikit-gstat/blob/bab68cf32551595bf66430e0354dbafba44d3573/skgstat/Variogram.py#L1453

that can already be used to return results. We can of course extend the output of these functions to bins edges etc., if needed.
So maybe @redhog you could give me some more insight, why it would be important to have a variogram without data and intermediate results as an object of its own? Then I maybe understand better what the purpose of this PR is.

If it's just about decreasing the in-memory size of the instance passed to `OrdinaryKriging`, another approach would be to make the Kriging class accept coordinates, values, and variogram parameters directly...
Or do I miss something here?

**Comment by redhog** [comment]
We have large datasets with multiple measurements stored in a PostGIS database. In our workflow, we generate variograms as a separate task where the user loads some dataset of measurements, selects some parameters and then reviews the plots of a set of variograms, one for each measurements, and when happy saves the variograms to the database (with a name). Multiple variograms (using e.g. different distance metrics or estimator) can be stored for the same measurement and dataset.

In later tasks, the user loads one of the variograms for each of their currently loaded measurements, selects a polygon and raster resolution, or set of positions, and interpolates the measurements to those positions.

We store the variograms by pickling them and storing the pickled bytes to a row in the database. We later load a dataset from the database, as well as associated variogram pickles that we unpickle and insert the values and coordinates into to do kriging. Storing the data twice - both as individual database rows, and inside a pickle of the variogram in one row, is actually impossible - the database driver crashed when I tried. It would also mean that we'd have to store it multiple times if the user generated multiple variograms with different metrics etc for the same measurement.

**Comment by redhog** [comment]
The idea of this class is that it encapsulates all the data that OrdinaryKriging needs, except for coordinates and values.

**Comment by mmaelicke** [comment]
OK I see. That makes the case clearer for me. 
I personally would still like to go for the solution to enhance the describe() output. If I got you right, that will serve your needs and make me happy as well.
Would that be fine for you?

**Comment by redhog** [comment]
If we can modify OrdinaryKrigin as per above, then that's actually better than my solution, as the describe() output can be stored as json.

However, ideally, all parameters to Variogram.__init__() should be output too, so that it is clear how the variogram got created (this would typically be shown in a info-dialog somewhere when you select a stored variogram).

**Comment by mmaelicke** [comment]
100% agree. Do you want to create an issue on this, or just commit the proposed changes here?

**Comment by redhog** [comment]
Hm, let's create an issue

**Pull request merged**
